### ISSUE TITLE
Error in reset-optimization

### ISSUE THREAD

**Issue by srussvoll** [wil3/gymfc#12]
In the reset-optimization branch, I get a long list of these errors:

> [Wrn] [QuadcopterWorldPlugin.cpp:533] Received size -1 less than the expected size of 20
> [Err] [QuadcopterWorldPlugin.cpp:384] Command not received t=0

before this line appears and everything seems to be working again:

> [Dbg] [QuadcopterWorldPlugin.cpp:558] Quadcopter controller online detected.

**Comment by wil3** [comment]
Hi @srussvoll what you are seeing is OK. This branch is still in active development, that particular Err should be a Wrn though didn't expect anyone to be using it. On this branch what you are looking for that would be bad is any failed asserts on the Python side. Basically there has been an issue where Gazebo sim seems to be stepping when it shouldn't be, the problem seems to be resolved but I'm going to keep testing it before merging to master. I suggest using the master branch in the mean time or expect verbose output and frequent changes on this branch.
